name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '7-2018-q2' # GNU ARM GCC version used by Nordic SDK 17.0.2
      
    - name: make
      run: make

    - uses: deka0106/upload-to-dropbox@v2
      with:
        dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        src: _build/nrf52840_xxaa.hex
        dest: /
        mode: overwrite
