name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc

    - uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '9-2019-q4' # GNU ARM GCC version used by Nordic SDK 17.0.2

    - name: make
      run: make
